import { SurveyResponse } from '../types';

export const INITIAL_MAURITANIA_RESPONSES: SurveyResponse[] = [
  {
    id: 'resp_mau_001',
    surveyId: 'survey_mauritania_dos',
    userName: 'Encuestada Nuadibú 1',
    userLanguage: 'fr',
    userCountry: 'Mauritania',
    submittedAt: '2026-10-04T10:15:00.000Z',
    answers: {
      m1: 'Acepto participar de forma voluntaria y acepto que se utilicen estos datos para realizar informes de DDHH',
      m2: '26-35',
      m3: 'Senegal',
      m4: 'Documentación regular',
      m5: 'Sí',
      m6: '1-2',
      m7: 'Trabajo ocasional o informal',
      m8: ['Falta de acceso o ingresos', 'Problemas familiares'],
      m9: ['Ninguna'],
      m10: 'No',
      m11: ['Ninguna'],
      m12: 'No',
      m13: 'No',
      m14: 'No',
      m15: 'Sí',
      m16: 'No',
      m17: ['Discriminación por origen o nacionalidad', 'Explotación laboral'],
      m18: 'Sí, a persona cercana',
      m19: 'Nada, no obtuve ninguna reparación',
      m20: 'Algunas veces',
      m21: 'Sí',
      m22: 'Falta de dinero',
      m23: 'Sí',
      m24: '',
      m25: 'Precaria',
      m26: ['Nacionalidad', 'Color de piel'],
      m27: 'Sí',
      m28: 'Sí',
      m29: 'Lo intento, pero no se me escucha',
      m30: 'Siempre',
      m31: 'A veces',
      m32: 'Siempre',
      m33: 'A veces',
      m34: 'Sí, algunas',
      m35: 'No',
      m36: 'No',
      m37: 'No',
      m38: ['Ninguna'],
      m39: 'No recuerda / no sabe',
      m40: 'No',
      m41: [],
      m42: []
    }
  },
  {
    id: 'resp_mau_002',
    surveyId: 'survey_mauritania_dos',
    userName: 'Encuestada Nuadibú 2',
    userLanguage: 'haa',
    userCountry: 'Mauritania',
    submittedAt: '2026-10-04T11:40:00.000Z',
    answers: {
      m1: 'Acepto participar de forma voluntaria y acepto que se utilicen estos datos para realizar informes de DDHH',
      m2: '18-25',
      m3: 'Mali',
      m4: 'Sin documentación o documentación vencida',
      m5: 'No',
      m6: 'Ninguna',
      m7: 'No tengo trabajo',
      m8: ['Conflicto armado o inseguridad', 'Violencia de género'],
      m9: ['Violencia armada', 'Amenazas o persecución'],
      m10: 'Sí',
      m11: ['Robo o extorsión', 'Violencia física', 'Hambre o falta de agua'],
      m12: 'Sí',
      m13: 'Sí',
      m14: 'Sí',
      m15: 'No',
      m16: '',
      m17: ['Violencia por parte de autoridades públicas', 'Amenaza de expulsión'],
      m18: 'Sí, a ONG / institución',
      m19: 'Caso sigue abierto / sin resolución',
      m20: 'Frecuentemente',
      m21: 'Sí',
      m22: 'Falta de documentación',
      m23: 'No',
      m24: 'Falta de documentación',
      m25: 'Hacinada',
      m26: ['Nacionalidad', 'Situación migratoria', 'Idioma o acento'],
      m27: 'Sí',
      m28: 'No',
      m29: '',
      m30: 'Siempre',
      m31: 'Siempre',
      m32: 'Siempre',
      m33: 'Siempre',
      m34: 'No',
      m35: 'No',
      m36: 'Sí',
      m37: 'Sí',
      m38: ['Violencia física', 'Violencia sexual'],
      m39: 'En el trayecto',
      m40: 'Sí',
      m41: ['ONG / organización humanitaria'],
      m42: ['No recibió respuesta']
    }
  },
  {
    id: 'resp_mau_003',
    surveyId: 'survey_mauritania_dos',
    userName: 'Encuestada Nuadibú 3',
    userLanguage: 'fr',
    userCountry: 'Mauritania',
    submittedAt: '2026-10-04T14:20:00.000Z',
    answers: {
      m1: 'Acepto participar de forma voluntaria y acepto que se utilicen estos datos para realizar informes de DDHH',
      m2: '36-50',
      m3: 'Guinea',
      m4: 'En tránsito',
      m5: 'Parcialmente',
      m6: '3-5',
      m7: 'Trabajo ocasional o informal',
      m8: ['Falta de acceso o ingresos', 'Falta de acceso a alimentación'],
      m9: ['Ninguna'],
      m10: 'Sí',
      m11: ['Hambre o falta de agua', 'Robo o extorsión'],
      m12: 'Sí',
      m13: 'No',
      m14: 'No',
      m15: 'Sí',
      m16: 'No',
      m17: ['Discriminación por origen o nacionalidad', 'Explotación laboral'],
      m18: 'No',
      m19: '',
      m20: 'Algunas veces',
      m21: 'Sí',
      m22: 'Falta de dinero',
      m23: 'Sí',
      m24: '',
      m25: 'Precaria',
      m26: ['Nacionalidad', 'Color de piel'],
      m27: 'Sí',
      m28: 'Sí',
      m29: 'Sí',
      m30: 'Siempre',
      m31: 'A veces',
      m32: 'A veces',
      m33: 'A veces',
      m34: 'Sí, varias',
      m35: 'No',
      m36: 'No',
      m37: 'Sí',
      m38: ['Coerción económica'],
      m39: 'En Mauritania',
      m40: 'No',
      m41: [],
      m42: []
    }
  },
  {
    id: 'resp_mau_004',
    surveyId: 'survey_mauritania_dos',
    userName: 'Encuestada Nuakchot 1',
    userLanguage: 'fr',
    userCountry: 'Mauritania',
    submittedAt: '2026-10-04T16:05:00.000Z',
    answers: {
      m1: 'Acepto participar de forma voluntaria y acepto que se utilicen estos datos para realizar informes de DDHH',
      m2: '26-35',
      m3: 'Costa de Marfil',
      m4: 'Documentación regular',
      m5: 'Sí',
      m6: '1-2',
      m7: 'Trabajo estable',
      m8: ['Falta de acceso o ingresos'],
      m9: ['Ninguna'],
      m10: 'No',
      m11: ['Ninguna'],
      m12: 'No',
      m13: 'No',
      m14: 'No',
      m15: 'Sí',
      m16: 'Sí',
      m17: ['Discriminación por origen o nacionalidad'],
      m18: 'No',
      m19: '',
      m20: 'Algunas veces',
      m21: 'No',
      m22: '',
      m23: 'Sí',
      m24: '',
      m25: 'Adecuada',
      m26: ['Idioma o acento'],
      m27: 'No',
      m28: 'Sí',
      m29: 'Sí',
      m30: 'A veces',
      m31: 'Nunca',
      m32: 'A veces',
      m33: 'Nunca',
      m34: 'Sí, varias',
      m35: 'No',
      m36: 'No',
      m37: 'No',
      m38: ['Ninguna'],
      m39: 'No recuerda / no sabe',
      m40: 'No',
      m41: [],
      m42: []
    }
  },
  {
    id: 'resp_mau_005',
    surveyId: 'survey_mauritania_dos',
    userName: 'Encuestada Nuadibú 4',
    userLanguage: 'haa',
    userCountry: 'Mauritania',
    submittedAt: '2026-10-05T09:12:00.000Z',
    answers: {
      m1: 'Acepto participar de forma voluntaria y acepto que se utilicen estos datos para realizar informes de DDHH',
      m2: '18-25',
      m3: 'Mali',
      m4: 'Sin documentación o documentación vencida',
      m5: 'Parcialmente',
      m6: '1-2',
      m7: 'No tengo trabajo',
      m8: ['Conflicto armado o inseguridad', 'Persecución o amenazas'],
      m9: ['Violencia física', 'Violencia sexual'],
      m10: 'Sí',
      m11: ['Violencia sexual', 'Detención', 'Separación familiar'],
      m12: 'Sí',
      m13: 'Sí',
      m14: 'No',
      m15: 'No',
      m16: '',
      m17: ['Violencia sexual', 'Violencia física', 'Amenaza de expulsión'],
      m18: 'Sí, a ONG / institución',
      m19: 'Caso sigue abierto / sin resolución',
      m20: 'Frecuentemente',
      m21: 'Sí',
      m22: 'Miedo',
      m23: 'No',
      m24: 'Discriminación',
      m25: 'Temporal',
      m26: ['Nacionalidad', 'Grupo étnico', 'Situación migratoria'],
      m27: 'Sí',
      m28: 'No',
      m29: '',
      m30: 'Siempre',
      m31: 'Siempre',
      m32: 'Siempre',
      m33: 'Siempre',
      m34: 'No',
      m35: 'Sí',
      m36: 'Sí',
      m37: 'Sí',
      m38: ['Violencia física', 'Violencia sexual', 'Control de movilidad'],
      m39: 'En Mauritania',
      m40: 'Sí',
      m41: ['ONG / organización humanitaria'],
      m42: ['Recibí protección o ayuda']
    }
  },
  {
    id: 'resp_mau_006',
    surveyId: 'survey_mauritania_dos',
    userName: 'Encuestada Nuadibú 5',
    userLanguage: 'es',
    userCountry: 'Mauritania',
    submittedAt: '2026-10-05T11:30:00.000Z',
    answers: {
      m1: 'Acepto participar de forma voluntaria y acepto que se utilicen estos datos para realizar informes de DDHH',
      m2: '26-35',
      m3: 'Senegal',
      m4: 'Documentación regular',
      m5: 'Sí',
      m6: '1-2',
      m7: 'Trabajo ocasional o informal',
      m8: ['Falta de acceso o ingresos'],
      m9: ['Ninguna'],
      m10: 'No',
      m11: ['Ninguna'],
      m12: 'No',
      m13: 'No',
      m14: 'No',
      m15: 'Sí',
      m16: 'Sí',
      m17: ['Discriminación por origen o nacionalidad'],
      m18: 'Sí, a persona cercana',
      m19: 'Nada, no obtuve ninguna reparación',
      m20: 'Nunca',
      m21: 'No',
      m22: '',
      m23: 'Sí',
      m24: '',
      m25: 'Adecuada',
      m26: ['Nacionalidad'],
      m27: 'No',
      m28: 'Sí',
      m29: 'Sí',
      m30: 'A veces',
      m31: 'Nunca',
      m32: 'A veces',
      m33: 'Nunca',
      m34: 'Sí, varias',
      m35: 'No',
      m36: 'No',
      m37: 'No',
      m38: ['Ninguna'],
      m39: 'No recuerda / no sabe',
      m40: 'No',
      m41: [],
      m42: []
    }
  },
  {
    id: 'resp_mau_007',
    surveyId: 'survey_mauritania_dos',
    userName: 'Encuestada Nuakchot 2',
    userLanguage: 'haa',
    userCountry: 'Mauritania',
    submittedAt: '2026-10-05T13:45:00.000Z',
    answers: {
      m1: 'Acepto participar de forma voluntaria y acepto que se utilicen estos datos para realizar informes de DDHH',
      m2: '36-50',
      m3: 'Mali',
      m4: 'Sin documentación o documentación vencida',
      m5: 'No',
      m6: '3-5',
      m7: 'Trabajo ocasional o informal',
      m8: ['Conflicto armado o inseguridad', 'Falta de acceso a alimentación'],
      m9: ['Violencia armada', 'Amenazas o persecución'],
      m10: 'Sí',
      m11: ['Robo o extorsión', 'Hambre o falta de agua'],
      m12: 'Sí',
      m13: 'Sí',
      m14: 'No',
      m15: 'Sí',
      m16: 'No',
      m17: ['Discriminación por origen o nacionalidad', 'Explotación laboral'],
      m18: 'No',
      m19: '',
      m20: 'Algunas veces',
      m21: 'Sí',
      m22: 'Falta de dinero',
      m23: 'No',
      m24: 'Falta de recursos',
      m25: 'Precaria',
      m26: ['Nacionalidad', 'Idioma o acento'],
      m27: 'Sí',
      m28: 'No',
      m29: '',
      m30: 'Siempre',
      m31: 'Siempre',
      m32: 'Siempre',
      m33: 'A veces',
      m34: 'Sí, algunas',
      m35: 'No',
      m36: 'Prefiero no responder',
      m37: 'Prefiero no responder',
      m38: ['Explotación laboral', 'Coerción económica'],
      m39: 'En Mauritania',
      m40: 'No pudo',
      m41: [],
      m42: []
    }
  },
  {
    id: 'resp_mau_008',
    surveyId: 'survey_mauritania_dos',
    userName: 'Encuestada Nuadibú 6',
    userLanguage: 'fr',
    userCountry: 'Mauritania',
    submittedAt: '2026-10-05T15:20:00.000Z',
    answers: {
      m1: 'Acepto participar de forma voluntaria y acepto que se utilicen estos datos para realizar informes de DDHH',
      m2: 'Más de 50',
      m3: 'Gambia',
      m4: 'Documentación regular',
      m5: 'Sí',
      m6: 'Más de 5',
      m7: 'Trabajo estable',
      m8: ['Falta de acceso o ingresos'],
      m9: ['Ninguna'],
      m10: 'No',
      m11: ['Ninguna'],
      m12: 'No',
      m13: 'No',
      m14: 'No',
      m15: 'Sí',
      m16: 'Sí',
      m17: ['Ninguna'],
      m18: 'No',
      m19: '',
      m20: 'Nunca',
      m21: 'No',
      m22: '',
      m23: 'Sí',
      m24: '',
      m25: 'Adecuada',
      m26: ['No'],
      m27: 'No',
      m28: 'Sí',
      m29: 'Sí',
      m30: 'A veces',
      m31: 'Nunca',
      m32: 'A veces',
      m33: 'Nunca',
      m34: 'Sí, varias',
      m35: 'No',
      m36: 'No',
      m37: 'No',
      m38: ['Ninguna'],
      m39: 'No recuerda / no sabe',
      m40: 'No',
      m41: [],
      m42: []
    }
  }
];
